name: CI/CD Pipeline for CRUD API

# Trigger the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/crud-api:latest
    # step 5 : Deploy 
  run-docker-container:
    needs: build-and-push-docker
    runs-on: ubuntu-latest  # Replace with `self-hosted` if using a self-hosted runner
    steps:
    # Step 1: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 2: Pull the Docker image
    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/crud-api:latest

    # Step 3: Stop and remove existing container
    - name: Stop and remove existing container
      run: |
        docker stop crud-api-container || true
        docker rm crud-api-container || true

    # Step 4: Run the Docker container
    - name: Run Docker container
      run: |
        docker run -d \
          --name crud-api-container \
          -p 5000:5000 \ 
          ${{ secrets.DOCKER_USERNAME }}/crud-api:latest
